Docker file steps to follow ->

Base ubuntu

sudo apt-get update
sudo apt install python3-pip
Install Git
GitClone ..
sudo pip3 install pymongo
sudo pip3 install newsapi-python
sudo pip3 install newspaper3k
sudo pip3 install pandas


./news-python-database-sentiment/SVM/getNews.sh